name: Tarea03 - ReleaseVersion

env:
  DOTNET_VERSION: '8.0'

on:
  push:
    tags:
      - 'v*' # Solo cuando se crean tags de versión

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          cd Bank
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: |
          cd Bank
          dotnet test Bank.Domain.Tests/Bank.Domain.Tests.csproj --configuration Release --no-build

      - name: Pack
        run: |
          cd Bank
          dotnet pack Bank.Domain/Bank.Domain.csproj -c Release \
            --no-build \
            -p:PackageVersion=${{ steps.get_version.outputs.VERSION }} \
            -o ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Bank/artifacts/*.nupkg"
          generate_release_notes: true
